name: Testing dotnet with emsdk arm64

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-dotnet-emsdk-arm64:
    runs-on: [self-hosted, Windows, ARM64, WASM]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build dotnet with emsdk arm64
        run: |
          git clone https://github.com/Windows-on-ARM-Experiments/emsdk
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          $env:EMSDK_PATH = $PWD.Path + "\emsdk"
          ./build.cmd -bl -os browser -subset mono+libs+packs -c Release