name: Testing dotnet with emsdk arm64

on:
  workflow_dispatch:

jobs:
  test-dotnet-emsdk-arm64:
    runs-on: [self-hosted, Windows, ARM64, WASM]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build dotnet with emsdk arm64
        run: ls